### ISSUE TITLE
seqCAT failed to read vcf

### ISSUE THREAD

**Issue by waemm** [fasterius/seqCAT#2]
Hi,

I get the following error when trying to load an ensemble VCF created by bcbio pipeline.

> create_profile("TD1731_1-619190094-A1_downsampled-ensemble.vcf.gz","TD1731_1-619190094-A1_downsampled")
Reading VCF file ...
Creating SNV profile ...
Error in `[<-.data.frame`(`*tmp*`, data$A2 == 0, "A2", value = c(NA_character_,  : 
  missing values are not allowed in subscripted assignments of data frames
In addition: Warning messages:
1: In .bcfHeaderAsSimpleList(header) :
  duplicate keys in header will be forced to unique rownames
2: In .bcfHeaderAsSimpleList(header) :
  duplicate keys in header will be forced to unique rownames
3: In .bcfHeaderAsSimpleList(header) :
  duplicate keys in header will be forced to unique rownames

I am using version 1.7.5

Any help would be appreciated

**Comment by fasterius** [comment]
Hi,

I have not used the bcbio pipeline myself, so I'm not familiar with their VCF output formats. Would you mind sending a subset of your failing VCF file, so I can try and troubleshoot it?
